version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: exploresg
      POSTGRES_USER: exploresguser
      POSTGRES_PASSWORD: exploresgpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/exploresg
      SPRING_DATASOURCE_USERNAME: exploresguser
      SPRING_DATASOURCE_PASSWORD: exploresgpass
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  pgdata:
